# https://codebeautify.org/yaml-validator
#.env add to docker-compose to default
## if you have ersonal environment for container 
## you can use: env_
# app:
#   images: image:v1
#   env_file:
#     - my_personal_env


    
version: '3.1'
services:

  app:
    image: extsand/terra.weather_docker
    ports:
      - ${APP_PORT}:5000
    restart: always    
  
